version: '3.8'

service:
  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:latest
    command:
      - '--path.rootfs=/host'          # This command tells the node exporter to run the metrics from the host file system.
    pid: host                          # We use the host pid namespace inside the container.
    volumes:
      - '/:/host:ro'                   # mount the host root file system inside the container as a read only volume.

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # a configuration file for prometheus that we will map it to the same file name in the container.
      - ./prometheus-data:/prometheus                    # create a folder 'prometheus' that saves data from prom and then save it locally on 'prometheus-data'
    command:
      - --config.file=/etc/prometheus/prometheus.yml           # This command to tell the prometheus container where to find the config file.

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-data.yml:var/lib/grafana
