global:
  scrape_interval: 15s            # This is how often prometheus is going to scrape data from node exporter

  scrape_configs:
    - job_name: node-exporter
      static_configs:
        - targets: [node_exporter:9100]    # in this case prometheus is going to scrape data from 'node_exporter' running on port 9100.
