apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate                      # in order to attach a new creatd pod to the existing volume, if the old one was destroyed.
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.admin.user }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.admin.password }}
          ports:
            - containerPort: {{ .Values.grafana.service.port }}