apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | lower }}-grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.port }}
  selector:
    app: grafana
