#This file defines a Kubernetes ConfigMap that holds the 
#Prometheus configuration file (prometheus.yml) as inline YAML content.
#It uses Helm templating to inject values from values.yaml.

{{- if .Values.prometheus.jenkins.host | lower }}

# This is a Helm conditional block.
# Which means only create this ConfigMap if the user provided a Jenkins host in values.yaml.
# This avoids creating a broken config when Jenkins integration isn’t used.

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  # This is the main Prometheus config file content stored as a key called prometheus.yaml inside the ConfigMap.
  # The | symbol means preserve line breaks (YAML multiline block).
  prometheus.yaml: |
    global:
      scrape_interval: 15s                     # Prometheus will scrape metrics every 15 seconds.

    scrape_configs:                            # This section defines which targets Prometheus scrapes.
      - job_name: 'netflix'
        metrics_path: /metrics
        static_configs:
          - targets: ['netflix-service.netflix.svc.cluster.local:3000']

      - job_name: 'prometheus'                 # Tells Prometheus to monitor itself.
        static_configs:
          - targets: ['localhost:9090']        # localhost:9090 is the port where Prometheus runs inside the container.

      - job_name: 'jenkins'                    # Appears in Prometheus UI for this target.
        metrics_path: /prometheus              # Prometheus plugin in Jenkins exposes metrics here.
        static_configs:                        # This is the Jenkins IP and port, injected from the values.yaml file.
          - targets: ['{{ .Values.prometheus.jenkins.host }}:{{ .Values.prometheus.jenkins.port }}']

{{- end }}
