apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name | lower }}-node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostPID: true
      volumes:
        - name: host
          hostPath:
            path: /
            type: Directory
      containers:
        - name: node-exporter
          image: {{ index .Values "node-exporter" "image" "repository" }}:{{ index .Values "node-exporter" "image" "tag" }}
          args:
            - "--path.rootfs=/host"
          volumeMounts:
            - name: host
              mountPath: /host
              readOnly: true
          ports:
            - containerPort: 9100
              hostPort: 9100