apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: {{ index .Values "kube-prometheus-stack" "prometheus" "service" "type" }}
  ports:
    - port: {{ index .Values "kube-prometheus-stack" "prometheus" "service" "port" }}
      targetPort: 9090
      nodePort: {{ index .Values "kube-prometheus-stack" "prometheus" "service" "nodePort" }}
  selector:
    app: prometheus