# servicemonitor-netflix.yaml (in Prometheus Helm chart templates/)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netflix-monitor
  namespace: monitoring  # Deploy in monitoring namespace
  labels:
    release: prometheus  # Must match Prometheus selector
spec:
  namespaceSelector:
    matchNames:
    - netflix  # Look for services in Netflix's namespace
  selector:
    matchLabels:
      app: netflix-app  # Netflix service label
  endpoints:
  - port: metrics  # Named port from Netflix service
    path: /metrics
    interval: 15s